package dms.pastor.chinesegame.extras.util;

import android.app.Activity;
import android.view.View;

//Generated by Android Studio.
public abstract class SystemUiHider {
    static final int FLAG_LAYOUT_IN_SCREEN_OLDER_DEVICES = 0x1;
    static final int FLAG_FULLSCREEN = 0x2;
    public static final int FLAG_HIDE_NAVIGATION = FLAG_FULLSCREEN | 0x4;

    private static final OnVisibilityChangeListener DUMMY_LISTENER = new OnVisibilityChangeListener() {
        @Override
        public void onVisibilityChange(boolean visible) {
        }
    };
    final Activity mActivity;
    final View mAnchorView;
    final int mFlags;
    OnVisibilityChangeListener mOnVisibilityChangeListener = DUMMY_LISTENER;

    SystemUiHider(Activity activity, View anchorView) {
        mActivity = activity;
        mAnchorView = anchorView;
        mFlags = dms.pastor.chinesegame.extras.RandomWordActivity.HIDER_FLAGS;
    }

    public static SystemUiHider getInstance(Activity activity, View anchorView) {
        return new SystemUiHiderHoneycomb(activity, anchorView);
    }

    public abstract void setup();
    protected abstract boolean isVisible();
    public abstract void hide();

    public abstract void show();

    public final void toggle() {
        if (isVisible()) {
            hide();
        } else {
            show();
        }
    }

    public final void setOnVisibilityChangeListener(OnVisibilityChangeListener listener) {
        if (listener == null) {
            listener = DUMMY_LISTENER;
        }

        mOnVisibilityChangeListener = listener;
    }

    public interface OnVisibilityChangeListener {
        void onVisibilityChange(boolean visible);
    }
}
